### ISSUE TITLE
Help with mathematical proof

### ISSUE THREAD

**Issue by binzhang** [sonsongithub/CoreAR#2]
I am sorry to ask questions here, but I don't know how to send message to you.
Would you please provide me with link explaining the Camera matrix from the homography matrix.

_CRGetDefectivePMatrixFromHomographyMatrix(p, pmat);
and
_CRAdjustTranslationParameterOfPMatrixOf2DCode(pmat, c, codeSize, inputImgWidth, inputImageHeight);

Is there strict mathematical proof related to the above algorithm?
Thank you.

**Comment by sonsongithub** [comment]
This page provides a simple suggestion to you, I think.
http://dsp.stackexchange.com/questions/2736/step-by-step-camera-pose-estimation-for-visual-tracking-and-planar-markers

**Comment by binzhang** [comment]
Thank you very much for your further reference,
After reading opencv's  document and your code, I still got questions and I
appreciate if you could help.
From two images, using four corner points, we could get homography matrix.
But how to decompose homography to opengl rotation&translation matrix?
The following code implements as the opencv documents describes:

Implementation  A: https://gist.github.com/inspirit/740979,

You choose the camera intrinsic matrix to be
( fx, 0, 0,
  0,  fy, 0,
  0,  0, 1)
where fx = CRGetFocalXLength(),
            fy = CRGetFocalYLength().
and using the image center as the origin while calculating homography.

But your code seems different in the
CRGetDefectivePamatrixFromHomographyMatrix() with the  Implementation A.
you have normalized two vectors (b[0], b[3], b[6]), (b[1], b[4], b[7]) ,
but in the implementation A and opencv document, It seems that the two
vectors normalization factor should be the same. That is || b[0], b[3],
b[6] ||  == || b[1],  b[4], b[7] ||. However as the program log shows,
these two magnitude of these two vectors are not equal. I wonder if I have
missed something.

Second,
I don't understand CRCalculateTranslationParameter(). Isn't the 4x4 matrix
already calcualted by the CRGetDefectivePMatrixFromHomographyMatrix?  Would
you please kindly help to explain this?

Thank you.

Cheers,
Bin Zhang

**Comment by sonsongithub** [comment]
> > That is || b[0], b[3], b[6] || == || b[1], b[4], b[7] ||. 

There are a lot of noises, such as distortion of lens, quantize noise of CCD, blur.
We can't get any good results from the real world.
So, we have to optimize some parameters which are obtained using a mathematical method like Levenberg-Marquardt method.

> > _CRCalculateTranslationParameter

_CRCalculateTranslationParameter adjust a position of image center and image size.

I can't teach it more than above. It's not so easy.
You should take a computer vision text.

Thank you.
